openapi: 3.0.3

info:
  version: 1.0.0
  title: E-Shop
  description: E-Shop REST API
  license:
    name: MIT
    url: https://spdx.org/licenses/MIT

tags:
  - name: catalog

servers:
  - url: '/api'

paths:
  "/products":
    get:
      tags:
        - catalog
      summary: Get product list
      parameters:
        - $ref: '#/components/parameters/product_list_per_page'
        - $ref: '#/components/parameters/page'
      responses:
        200:
          $ref: '#/components/responses/pagination-product-list'

  "/products/{id}":
    get:
      tags:
        - catalog
      summary: Get Product information
      parameters:
        - name: id
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/uuid'
      responses:
        200:
          description: Product
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/product'
              examples:
                default:
                  $ref: '#/components/examples/product'
        404:
          $ref: '#/components/responses/not-found'

  "/categories":
    get:
      tags:
        - catalog
      summary: Get Category list
      responses:
        200:
          description: Category List
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/category'
              examples:
                default:
                  $ref: '#/components/examples/categories'

  "/categories/tree":
    get:
      tags:
        - catalog
      summary: Get Category hierarchy
      responses:
        200:
          description: Category hierarchy
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/categoryTree'
              examples:
                default:
                  $ref: '#/components/examples/categoryTree'

  "/categories/{id}":
    get:
      tags:
        - catalog
      summary: Get Category information
      parameters:
        - $ref: '#/components/parameters/id'
      responses:
        200:
          description: Category Information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/category'
              examples:
                default:
                  $ref: '#/components/examples/category'
        404:
          $ref: '#/components/responses/not-found'

  "/categories/{id}/products":
    get:
      tags:
        - catalog
      summary: Get Product list for given Category
      parameters:
        - $ref: '#/components/parameters/product_list_per_page'
        - $ref: '#/components/parameters/page'
        - $ref: '#/components/parameters/id'
      responses:
        200:
          $ref: '#/components/responses/pagination-product-list'
        404:
          $ref: '#/components/responses/not-found'

components:
  schemas:
    product:
      type: object
      properties:
        id:
          $ref: '#/components/schemas/uuid'
        name:
          type: string
          example: Sneakers
        sku:
          type: array
          items:
            $ref: '#/components/schemas/sku'
      required:
        - id
        - name
        - sku

    sku:
      description: Stock Keeping Unit
      type: object
      properties:
        price:
          $ref: '#/components/schemas/money'
        ean:
          $ref: '#/components/schemas/ean'
      required:
        - price
        - ean

    uuid:
      type: string
      format: uuid
      example: 123e4567-e89b-12d3-a456-426614174000

    ean:
      type: string
      format: gtin13
      description: Global Trade Item Number (GTIN-13)
      example: '5901234123457'

    money:
      type: object
      properties:
        amount:
          type: number
          format: decimal
          minimum: 0
          example: 100.1
        currency:
          type: string
          description: 3 letter currency code as defined by ISO-4217
          format: iso-4217
          example: EUR
      required:
        - amount
        - currency

    base-error:
      type: object
      properties:
        status:
          type: integer
          minimum: 100
          maximum: 600
          exclusiveMaximum: true
          example: 404
        detail:
          type: string
          example: Resource not found
      required:
        - status
        - detail

    pagination-result:
      type: object
      properties:
        page:
          type: integer
          minimum: 0
          example: 2
        perPage:
          type: integer
          minimum: 1
          example: 30
        totalItems:
          type: integer
          minimum: 0
          example: 63
        totalPages:
          type: integer
          minimum: 0
          example: 3

    category:
      type: object
      properties:
        id:
          $ref: '#/components/schemas/uuid'
        name:
          type: string
          example: Sneakers
        parentId:
          allOf:
            - $ref: '#/components/schemas/uuid'
            - nullable: true
      required:
        - id
        - name

    categoryTree:
      type: object
      properties:
        id:
          $ref: '#/components/schemas/uuid'
        name:
          type: string
          example: Sneakers
        children:
          type: array
          items:
            $ref: '#/components/schemas/categoryTree'
      required:
        - id
        - name

  responses:
    not-found:
      description: Resource not found
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/base-error"
          examples:
            default:
              $ref: '#/components/examples/not-found'

    pagination-product-list:
      description: Product List
      content:
        application/json:
          schema:
            allOf:
              - $ref: '#/components/schemas/pagination-result'
              - type: object
                properties:
                  items:
                    type: array
                    items:
                      $ref: '#/components/schemas/product'

  parameters:
    per_page:
      name: per_page
      description: Results per page
      in: query
      schema:
        type: integer
        maximum: 100
        minimum: 1
        default: 30
    product_list_per_page:
      name: per_page
      description: Results per page
      in: query
      schema:
        type: integer
        maximum: 50
        minimum: 1
        default: 30
    page:
      name: page
      description: Page number of the results to fetch
      in: query
      schema:
        type: integer
        minimum: 1
        default: 1
    id:
      name: id
      in: path
      required: true
      schema:
        $ref: '#/components/schemas/uuid'

  examples:
    product:
      value:
        uuid: 123e4567-e89b-12d3-a456-426614174000
        name: Sneakers
        sku:
          - ean: "5901234123457"
            price:
              amount: 342.35
              currency: USD

    category:
      value:
        id: 9b455ac1-1aa5-497f-a948-ea7a940ba359
        name: 'Clothes'
        parentId: 6842f43b-dfaa-4e4d-b4e2-bd7896c0bd05

    categories:
      value:
        - id: 9b455ac1-1aa5-497f-a948-ea7a940ba359
          name: 'Sneakers'
          parentId: 6842f43b-dfaa-4e4d-b4e2-bd7896c0bd05
        - id: 6842f43b-dfaa-4e4d-b4e2-bd7896c0bd05
          name: 'Clothes'
          parentId: null

    categoryTree:
      value:
        - id: 6842f43b-dfaa-4e4d-b4e2-bd7896c0bd05
          name: 'Clothes'
          children:
            - id: 9b455ac1-1aa5-497f-a948-ea7a940ba359
              name: 'Sneakers'
              children:
                - id: 9b455ac1-1aa5-497f-a948-ea7a940ba359
                  name: 'Running'
                  children: []
            - id: 818162f5-cf42-44ec-9eff-64d1a19b7b8d
              name: 'Shorts'
              children: []
        - id: 592ab0c8-343d-490c-b47a-20583d1f32d3
          name: 'Accessories'
          children: []

    not-found:
      value:
        status: 404
        detail: Resource not found
