openapi: 3.0.3

info:
  version: 1.0.0
  title: E-Shop
  description: E-Shop REST API
  license:
    name: MIT
    url: https://spdx.org/licenses/MIT

tags:
  - name: catalog
  - name: customer
  - name: cart

servers:
  - url: '/api'

paths:
  "/products":
    get:
      tags:
        - catalog
      summary: Get product list
      parameters:
        - $ref: '#/components/parameters/product_list_per_page'
        - $ref: '#/components/parameters/page'
      responses:
        200:
          $ref: '#/components/responses/pagination-product-list'

  "/products/{id}":
    get:
      tags:
        - catalog
      summary: Get Product information
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            example: 1
      responses:
        200:
          description: Product
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/product'
              examples:
                default:
                  $ref: '#/components/examples/product'
        404:
          $ref: '#/components/responses/not-found'

  "/categories":
    get:
      tags:
        - catalog
      summary: Get Category list
      responses:
        200:
          description: Category List
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/category'
              examples:
                default:
                  $ref: '#/components/examples/categories'

  "/categories/tree":
    get:
      tags:
        - catalog
      summary: Get Category hierarchy
      responses:
        200:
          description: Category hierarchy
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/categoryTree'
              examples:
                default:
                  $ref: '#/components/examples/categoryTree'

  "/categories/{id}":
    get:
      tags:
        - catalog
      summary: Get Category information
      parameters:
        - $ref: '#/components/parameters/id'
      responses:
        200:
          description: Category Information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/category'
              examples:
                default:
                  $ref: '#/components/examples/category'
        404:
          $ref: '#/components/responses/not-found'

  "/categories/{id}/products":
    get:
      tags:
        - catalog
      summary: Get Product list for given Category
      parameters:
        - $ref: '#/components/parameters/product_list_per_page'
        - $ref: '#/components/parameters/page'
        - $ref: '#/components/parameters/id'
      responses:
        200:
          $ref: '#/components/responses/pagination-product-list'
        404:
          $ref: '#/components/responses/not-found'

  "/customers":
    post:
      tags:
        - customer
      summary: Register new customer
      requestBody:
        $ref: '#/components/requestBodies/new-customer'
      responses:
        201:
          $ref: '#/components/schemas/customer'
        400:
          $ref: '#/components/responses/validation-error'

  "/customers/current":
    get:
      tags:
        - customer
      summary: Get the authenticated customer
      responses:
        200:
          $ref: '#/components/responses/authenticated-customer'
        401:
          $ref: '#/components/responses/requires-authentication'

    put:
      tags:
        - customer
      summary: Update the authenticated customer
      requestBody:
        $ref: '#/components/requestBodies/update-customer'
      responses:
        200:
          description: Customer updated
        400:
          $ref: '#/components/responses/validation-error'
        401:
          $ref: '#/components/responses/requires-authentication'

  "/cart":
    get:
      tags:
        - cart
      summary: Get cart for the authenticated customer
      responses:
        200:
          $ref: '#/components/responses/cart'
        401:
          $ref: '#/components/responses/requires-authentication'
        403:
          $ref: '#/components/responses/forbidden'

  "/cart/items":
    put:
      tags:
        - cart
      summary: Add new item to cart of authorized customer or
        change quantity of already existed in cart item, if item
        with the given EAN already exist in the cart
      requestBody:
        $ref: '#/components/requestBodies/upsert-cart-item'
      responses:
        200:
          $ref: '#/components/responses/cart'
        401:
          $ref: '#/components/responses/requires-authentication'
        403:
          $ref: '#/components/responses/forbidden'

components:
  schemas:
    product:
      type: object
      properties:
        id:
          type: string
          example: 1
        name:
          type: string
          example: Sneakers
        sku:
          type: array
          items:
            $ref: '#/components/schemas/sku'
      required:
        - id
        - name
        - sku

    sku:
      description: Stock Keeping Unit
      type: object
      properties:
        price:
          $ref: '#/components/schemas/money'
        ean:
          $ref: '#/components/schemas/ean'
        quantity:
          type: integer
          minimum: 0
          description: Available quantity for purchase
          example: 12
      required:
        - price
        - ean
        - quantity

    ean:
      type: string
      format: gtin13
      description: Global Trade Item Number (GTIN-13)
      example: '5901234123457'

    money:
      type: object
      properties:
        amount:
          type: number
          format: decimal
          minimum: 0
          example: 100.1
        currency:
          type: string
          description: 3 letter currency code as defined by ISO-4217
          format: iso-4217
          example: EUR
      required:
        - amount
        - currency

    base-error:
      type: object
      properties:
        status:
          type: integer
          minimum: 100
          maximum: 600
          exclusiveMaximum: true
          example: 404
        detail:
          type: string
          example: Resource not found
      required:
        - status
        - detail

    pagination-result:
      type: object
      properties:
        page:
          type: integer
          minimum: 0
          example: 2
        perPage:
          type: integer
          minimum: 1
          example: 30
        totalItems:
          type: integer
          minimum: 0
          example: 63
        totalPages:
          type: integer
          minimum: 0
          example: 3

    category:
      type: object
      properties:
        id:
          type: string
          example: 1
        name:
          type: string
          example: Sneakers
        parentId:
          type: string
          example: 1
          nullable: true
      required:
        - id
        - name

    categoryTree:
      type: object
      properties:
        id:
          type: string
          example: 1
        name:
          type: string
          example: Sneakers
        children:
          type: array
          items:
            $ref: '#/components/schemas/categoryTree'
      required:
        - id
        - name

    base-customer:
      type: object
      description: Customer
      properties:
        firstname:
          type: string
          example: Rick
        lastname:
          type: string
          example: Sanchez
        email:
          type: string
          format: email
          example: rick-sanchez@example.com
        birthday:
          allOf:
            - $ref: '#/components/schemas/date'
            - nullable: true
              example: '1989-10-21'
      required:
        - firstname
        - lastname
        - email

    customer:
      allOf:
        - type: object
          properties:
            id:
              type: string
              example: 1
        - $ref: '#/components/schemas/base-customer'

    new-customer:
      allOf:
        - $ref: '#/components/schemas/base-customer'
        - type: object
          properties:
            password:
              type: string
          required:
            - password

    date:
      type: string
      format: date
      example: 2000-07-21

    cart:
      type: object
      properties:
        id:
          type: string
          example: 1234
        items:
          type: array
          items:
            $ref: '#/components/schemas/cart-item'

    cart-item:
      type: object
      properties:
        ean:
          $ref: '#/components/schemas/ean'
        quantity:
          $ref: '#/components/schemas/cart-item-quantity'
        productName:
          type: string
          example: Sneakers

    cart-item-quantity:
      type: integer
      minimum: 1
      example: 7

  requestBodies:
    new-customer:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/new-customer'

    update-customer:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/base-customer'

    upsert-cart-item:
      content:
        application/json:
          schema:
            type: object
            properties:
              ean:
                $ref: '#/components/schemas/ean'
              quantity:
                $ref: '#/components/schemas/cart-item-quantity'

  responses:
    not-found:
      description: Resource not found
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/base-error"
          examples:
            default:
              $ref: '#/components/examples/not-found'

    requires-authentication:
      description: Requires authentication

    forbidden:
      description: Forbidden

    pagination-product-list:
      description: Product List
      content:
        application/json:
          schema:
            allOf:
              - $ref: '#/components/schemas/pagination-result'
              - type: object
                properties:
                  items:
                    type: array
                    items:
                      $ref: '#/components/schemas/product'

    customer:
      description: Customer
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/customer'

    authenticated-customer:
      description: Authenticated Customer
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/customer'

    cart:
      description: Cart
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/cart'

    validation-error:
      description: Validation Errors
      content:
        application/json:
          schema:
            type: object
            properties:
              errors:
                type: array
                items:
                  type: object
                  properties:
                    field:
                      type: string
                      example: email
                    message:
                      type: string
                      example: Invalid email format

  parameters:
    per_page:
      name: per_page
      description: Results per page
      in: query
      schema:
        type: integer
        maximum: 100
        minimum: 1
        default: 30
    product_list_per_page:
      name: per_page
      description: Results per page
      in: query
      schema:
        type: integer
        maximum: 50
        minimum: 1
        default: 30
    page:
      name: page
      description: Page number of the results to fetch
      in: query
      schema:
        type: integer
        minimum: 1
        default: 1
    id:
      name: id
      in: path
      required: true
      schema:
        type: string
        example: 1

  examples:
    product:
      value:
        id: 1
        name: Sneakers
        sku:
          - ean: "5901234123457"
            price:
              amount: 342.35
              currency: USD

    category:
      value:
        id: 1
        name: 'Clothes'
        parentId: 2

    categories:
      value:
        - id: 1
          name: 'Clothes'
          parentId: null
        - id: 2
          name: 'Sneakers'
          parentId: 1

    categoryTree:
      value:
        - id: 1
          name: 'Clothes'
          children:
            - id: 2
              name: 'Sneakers'
              children:
                - id: 3
                  name: 'Running'
                  children: []
            - id: 4
              name: 'Shorts'
              children: []
        - id: 5
          name: 'Accessories'
          children: []

    not-found:
      value:
        status: 404
        detail: Resource not found
